yolo_model:

  config_file:
    name: tiny-yolo-bumblebee-190319.cfg
  weight_file:
    name: tiny-yolo-bumblebee-190319_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - dice1
      - dice2
      - dice5
      - dice6
      - nhipata
