subscribers:

  camera_reading:
    topic: /anahita/front_camera/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /anahita/check_for_objects

publishers:

  object_detector:
    topic: /anahita/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /anahita/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /anahita/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
