yolo_model:

  config_file:
    name: tiny-yolo-vampire-170519.cfg
  weight_file:
    name: tiny-yolo-vampire-170519_1400.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - vampire
